default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doctor_portal_development
  username: doctor_portal
  password: 123456

test:
  <<: *default
  database: doctor_portal_test

production:
  <<: *default
  database: doctor_portal_production
  username: doctor_portal
  password: <%= ENV["DOCTOR_PORTAL_DATABASE_PASSWORD"] %>
